# Generated by Django 6.0.6 on 2026-07-04 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_initial'),
        ('funerals', '0001_initial'),
        ('members', '0002_alter_member_membership_number'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('amount_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gift_item', models.CharField(blank=True, help_text="e.g. '2 bags of rice', 'a cow' — blank if cash only.", max_length=255)),
                ('estimated_item_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('other', 'Other'), ('not_applicable', 'Not Applicable (item only)')], default='cash', max_length=20)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('client_op_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('donor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_donations_given', to='members.member')),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_donations', to='funerals.funeralevent')),
                ('recipient_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='families.family')),
            ],
            options={
                'ordering': ['-given_at'],
                'indexes': [models.Index(fields=['community', 'funeral_event'], name='gifts_giftd_communi_7ddb27_idx')],
            },
        ),
    ]
