# Generated by Django 6.0.6 on 2026-07-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_giftdonation_collected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdonation',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
