# Generated by Django 6.0.6 on 2026-07-05 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_initial'),
        ('funerals', '0002_contributionpayment_printed_at'),
        ('gifts', '0003_giftdonation_printed_at'),
        ('members', '0003_member_linked_user'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdonation',
            name='connected_relative_name',
            field=models.CharField(blank=True, help_text="The deceased's relative this guest attended on account of, as the cashier was told it.", max_length=255),
        ),
        migrations.AddField(
            model_name='giftdonation',
            name='donor_category',
            field=models.CharField(choices=[('guest', 'Guest'), ('town_leader', 'Town Leader (King/Elder)'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='giftdonation',
            name='donor_hometown',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='giftdonation',
            index=models.Index(fields=['funeral_event', 'donor_category'], name='gifts_giftd_funeral_4aa600_idx'),
        ),
    ]
