# Generated by Django 6.0.6 on 2026-07-05 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0002_contributionpayment_printed_at'),
        ('gifts', '0004_giftdonation_connected_relative_name_and_more'),
        ('members', '0003_member_linked_user'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdonation',
            name='received_by_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_received', to='members.member'),
        ),
        migrations.CreateModel(
            name='DonationAccountRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_account_registrations', to='funerals.funeralevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_account_registrations', to='members.member')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('funeral_event', 'member'), name='one_donation_registration_per_member_per_funeral')],
            },
        ),
    ]
