# Generated by Django 6.0.6 on 2026-07-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_giftdonation_received_by_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdonation',
            name='relationship_to_recipient',
            field=models.CharField(blank=True, help_text="The donor's relationship to whoever received this gift (e.g. 'Friend', 'Cousin', 'Workmate').", max_length=100),
        ),
    ]
