# Generated by Django 6.0.6 on 2026-07-28 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_alter_familyauditlog_action'),
        ('funerals', '0013_contributionpayment_funerals_co_paid_at_16a0cd_idx'),
        ('gifts', '0006_giftdonation_relationship_to_recipient'),
        ('members', '0006_member_email'),
        ('tenants', '0012_community_required_funeral_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='giftdonation',
            index=models.Index(fields=['given_at'], name='gifts_giftd_given_a_ce0a0d_idx'),
        ),
    ]
