# Generated by Django 6.0.6 on 2026-08-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0007_giftdonation_gifts_giftd_given_a_ce0a0d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdonation',
            name='collector_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
