# Generated by Django 6.0.6 on 2026-09-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0008_giftdonation_collector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdonation',
            name='delegation_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
