# Generated by Django 6.0.6 on 2026-07-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneotp_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'System Super Administrator'), ('platform_admin', 'Platform Administrator'), ('community_admin', 'Community Administrator'), ('traditional_leader', 'Traditional Leader (Chief)'), ('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('auditor', 'Auditor'), ('collector', 'Collector'), ('family_head', 'Family Head'), ('family_secretary', 'Family Secretary'), ('family_treasurer', 'Family Treasurer'), ('community_member', 'Community Member'), ('guest', 'Guest'), ('bereaved_rep', 'Bereaved Family Representative'), ('notification_officer', 'Notification Officer')], default='guest', max_length=32),
        ),
    ]
