# Generated by Django 6.0.6 on 2026-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_context',
            field=models.CharField(choices=[('executive', 'Executive'), ('personal', 'Personal')], default='executive', max_length=20),
        ),
    ]
