# Generated by Django 6.0.6 on 2026-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_active_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_admin_capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
