# Generated by Django 6.0.6 on 2026-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_platform_admin_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
