# Generated by Django 6.0.6 on 2026-09-29 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_consolidate_roles'),
        ('families', '0006_bereavedrepassignment'),
        ('tenants', '0024_community_role_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('base_role', models.CharField(choices=[('platform_admin', 'Platform Administrator'), ('community_admin', 'Community Administrator'), ('traditional_leader', 'Traditional Leader (Chief)'), ('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('auditor', 'Auditor'), ('collector', 'Collector'), ('arrears_collector', 'Community Arrears Officer'), ('family_head', 'Family Head'), ('family_secretary', 'Family Secretary'), ('family_treasurer', 'Family Treasurer'), ('community_member', 'Community Member'), ('guest', 'Guest'), ('bereaved_rep', 'Bereaved Family Representative'), ('notification_officer', 'Notification Officer'), ('family_registration_officer', 'Family Registration Officer'), ('town_registration_officer', 'Town Elders Registration Officer'), ('community_registration_desk', 'Community Registration Desk'), ('family_arrears_officer', 'Family Arrears Officer'), ('town_elders_arrears_officer', 'Town Elders Arrears Officer'), ('gift_collector', 'Guest Contribution Collector')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='tenants.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, help_text='Null = a community-level role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='families.family')),
            ],
            options={
                'ordering': ['family__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='accounts.customrole'),
        ),
        migrations.AddConstraint(
            model_name='customrole',
            constraint=models.UniqueConstraint(fields=('community', 'family', 'name'), name='uniq_custom_role_name_per_scope'),
        ),
    ]
