# Generated by Django 6.0.6 on 2026-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customrole_base_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Administrator'), ('community_admin', 'Community Administrator'), ('traditional_leader', 'Traditional Leader (Chief)'), ('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('auditor', 'Auditor'), ('collector', 'Collector'), ('arrears_collector', 'Community Arrears Officer'), ('family_head', 'Family Head'), ('family_secretary', 'Family Secretary'), ('family_treasurer', 'Family Treasurer'), ('community_member', 'Community Member'), ('guest', 'Guest'), ('bereaved_rep', 'Bereaved Family Representative'), ('notification_officer', 'Notification Officer'), ('family_registration_officer', 'Family Registration Officer'), ('town_registration_officer', 'Town Elders Registration Officer'), ('community_registration_desk', 'Community Registration Desk'), ('family_arrears_officer', 'Family Arrears Officer'), ('town_elders_arrears_officer', 'Town Elders Arrears Officer'), ('gift_collector', 'Guest Contribution Collector'), ('welfare_manager', 'Community Welfare Manager'), ('family_welfare_manager', 'Family Welfare Manager')], default='community_member', max_length=32),
        ),
    ]
