# Generated by Django 6.0.6 on 2026-07-04 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_general_male_amount', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('default_general_female_amount', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
