# Generated by Django 6.0.6 on 2026-07-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='default_family_head_amount',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='community',
            name='default_family_junior_amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='community',
            name='default_family_senior_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='community',
            name='default_family_woman_amount',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
        ),
        migrations.AddField(
            model_name='community',
            name='default_town_leader_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
