# Generated by Django 6.0.6 on 2026-07-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_community_default_family_head_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='access_plan',
            field=models.CharField(choices=[('ongoing', 'Ongoing (permanent)'), ('single_funeral', 'Single Funeral (temporary)'), ('time_limited', 'Time-Limited (temporary)')], default='ongoing', max_length=20),
        ),
    ]
