# Generated by Django 6.0.6 on 2026-07-21 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_community_access_expires_at_community_access_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank Account')], max_length=20)),
                ('provider_name', models.CharField(help_text="e.g. MTN Mobile Money, Vodafone Cash, or the bank's name", max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='tenants.community')),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
