# Generated by Django 6.0.6 on 2026-07-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_announcement_announcementreviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='featured_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='homepage_feature_requested',
            field=models.BooleanField(default=False),
        ),
    ]
