# Generated by Django 6.0.6 on 2026-07-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_featureflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='community_logos/'),
        ),
        migrations.AddField(
            model_name='community',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex color, e.g. #2F5233', max_length=7),
        ),
        migrations.AddField(
            model_name='community',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Hex color, e.g. #B8860B', max_length=7),
        ),
        migrations.AddField(
            model_name='community',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
