# Generated by Django 6.0.6 on 2026-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_community_logo_community_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='required_funeral_approvals',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
