# Generated by Django 6.0.6 on 2026-09-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_community_required_funeral_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='default_town_elder_chief_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='default_town_elder_linguist_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='default_town_elder_other_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='default_town_elder_queen_mother_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
