# Generated by Django 6.0.6 on 2026-09-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_community_default_town_elder_chief_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='default_asupede_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
