# Generated by Django 6.0.6 on 2026-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_community_last_subscription_reminder_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='community',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='community',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='community',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='community',
            name='estimated_population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='registration_notes',
            field=models.TextField(blank=True, help_text='Why this community is signing up, or anything the Platform Admin should know'),
        ),
        migrations.AddField(
            model_name='community',
            name='traditional_authority_name',
            field=models.CharField(blank=True, help_text="e.g. the reigning chief's name and title", max_length=255),
        ),
    ]
