# Generated by Django 6.0.6 on 2026-09-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_community_address_community_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='homepage_videos/'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_images/'),
        ),
    ]
