# Generated by Django 6.0.6 on 2026-09-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0022_inlawcontributionrequest_inlawobligation_and_more'),
        ('tenants', '0017_homepageimage_video_alter_homepageimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='funeral_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='funerals.funeralevent'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='announcement_videos/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, help_text='A link to a hosted video (YouTube, Vimeo, or similar) — an alternative to uploading a video file directly.'),
        ),
    ]
