# Generated by Django 6.0.6 on 2026-09-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_communitybackuprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='subscription_plan',
            field=models.CharField(choices=[('single_funeral', 'Single Funeral'), ('community', 'Community'), ('multi_community', 'Multi-Community')], default='community', max_length=20),
        ),
    ]
