# Generated by Django 6.0.6 on 2026-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_replace_subscription_plan_with_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='role_titles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
