# Generated by Django 6.0.6 on 2026-07-07 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_family_family_secretary_family_family_treasurer_and_more'),
        ('family_funds', '0001_initial'),
        ('funerals', '0003_funeralevent_deceased_date_of_birth'),
        ('members', '0003_member_linked_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyFuneralExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_contact', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_purchased', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funeral_expenses', to='families.family')),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_expenses', to='funerals.funeralevent')),
                ('paid_by_member', models.ForeignKey(blank=True, help_text='Which family member actually paid/disbursed the money for this purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funeral_expenses_paid', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_purchased', '-created_at'],
                'indexes': [models.Index(fields=['family', 'funeral_event'], name='family_fund_family__77be2d_idx')],
            },
        ),
    ]
