# Generated by Django 6.0.6 on 2026-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_funds', '0002_familyfuneralexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyfuneralexpense',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('contributions', 'Community/Family Contributions'), ('gifts', 'Gifts & Donations'), ('other', "Other (family's own money, etc.)")], default='', max_length=20),
        ),
    ]
