# Generated by Django 6.0.6 on 2026-07-04 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_initial'),
        ('members', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_type', models.CharField(choices=[('own_family', 'Own Family Rate'), ('general', 'General Rate')], max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_obligations', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('other', 'Other')], max_length=20)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('client_op_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='funerals.contributionobligation')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='FuneralEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deceased_name', models.CharField(max_length=255)),
                ('deceased_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_death', models.DateField()),
                ('burial_date', models.DateField(blank=True, null=True)),
                ('funeral_date', models.DateField(blank=True, null=True)),
                ('collection_start_date', models.DateField()),
                ('collection_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('own_family_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_male_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_female_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funerals', to='tenants.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deceased_family', models.ForeignKey(help_text='Members of this family pay the own-family rate; everyone else pays the general rate.', on_delete=django.db.models.deletion.PROTECT, related_name='funerals', to='families.family')),
            ],
            options={
                'ordering': ['-date_of_death'],
            },
        ),
        migrations.AddField(
            model_name='contributionobligation',
            name='funeral_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='funerals.funeralevent'),
        ),
        migrations.AddIndex(
            model_name='funeralevent',
            index=models.Index(fields=['community', 'status'], name='funerals_fu_communi_66607a_idx'),
        ),
        migrations.AddIndex(
            model_name='contributionobligation',
            index=models.Index(fields=['community', 'funeral_event', 'rate_type'], name='funerals_co_communi_b99a18_idx'),
        ),
        migrations.AddIndex(
            model_name='contributionobligation',
            index=models.Index(fields=['member'], name='funerals_co_member__e7e7ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='contributionobligation',
            constraint=models.UniqueConstraint(fields=('funeral_event', 'member'), name='one_obligation_per_member_per_funeral'),
        ),
    ]
