# Generated by Django 6.0.6 on 2026-07-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0002_contributionpayment_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='deceased_date_of_birth',
            field=models.DateField(blank=True, help_text="The deceased's own date of birth — shown on receipts instead of date of death.", null=True),
        ),
    ]
