# Generated by Django 6.0.6 on 2026-07-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0003_funeralevent_deceased_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='family_head_amount',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='family_junior_amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='family_senior_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='family_woman_amount',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='town_leader_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
