# Generated by Django 6.0.6 on 2026-07-15 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0004_funeralevent_family_head_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralevent',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='FuneralApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='funerals.funeralevent')),
            ],
            options={
                'ordering': ['approved_at'],
                'constraints': [models.UniqueConstraint(fields=('funeral_event', 'approved_by'), name='one_approval_per_person_per_funeral')],
            },
        ),
    ]
