# Generated by Django 6.0.6 on 2026-07-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0007_funeraldeskassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeraldeskassignment',
            name='desk_type',
            field=models.CharField(choices=[('community', 'Community Ledger Desk'), ('elders', 'Town Elders Desk'), ('guest', 'Guest Desk'), ('family', 'Family Desk')], max_length=20),
        ),
    ]
