# Generated by Django 6.0.6 on 2026-07-21 01:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0008_alter_funeraldeskassignment_desk_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tribute_message', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='memorial_photos/')),
                ('show_contribution_total', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('funeral_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_page', to='funerals.funeralevent')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialTribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memorial_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='funerals.memorialpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
