# Generated by Django 6.0.6 on 2026-07-23 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0010_paymentreversal'),
        ('members', '0006_member_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralCommitteePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('appointed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_positions', to='funerals.funeralevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funeral_committee_positions', to='members.member')),
            ],
            options={
                'ordering': ['title', 'appointed_at'],
            },
        ),
    ]
