# Generated by Django 6.0.6 on 2026-07-28 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0012_funeraldeskassignment_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contributionpayment',
            index=models.Index(fields=['paid_at'], name='funerals_co_paid_at_16a0cd_idx'),
        ),
    ]
