# Generated by Django 6.0.6 on 2026-08-12 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0013_contributionpayment_funerals_co_paid_at_16a0cd_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralDeskAssignmentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_by_role', models.CharField(max_length=32)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('desk_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='funerals.funeraldeskassignment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('desk_assignment', 'approved_by'), name='one_desk_assignment_approval_per_person')],
            },
        ),
    ]
