# Generated by Django 6.0.6 on 2026-08-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0014_funeraldeskassignmentapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionpayment',
            name='collector_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
