# Generated by Django 6.0.6 on 2026-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0015_contributionpayment_collector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('other', 'Other'), ('wallet', 'Wallet credit')], max_length=20),
        ),
    ]
