# Generated by Django 6.0.6 on 2026-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0016_alter_contributionpayment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionobligation',
            name='rate_type',
            field=models.CharField(choices=[('own_family', 'Own Family Rate'), ('general', 'General Rate'), ('town_elder', 'Town Elder Rate')], max_length=20),
        ),
    ]
