# Generated by Django 6.0.6 on 2026-09-09 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_bereavedrepassignment'),
        ('funerals', '0017_alter_contributionobligation_rate_type'),
        ('tenants', '0012_community_required_funeral_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('general', 'Community Ledger'), ('own_family', 'Family Ledger'), ('town_elder', 'Town Elders Ledger')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_wallets', to='tenants.community')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_wallet', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('credit', 'Credit (a contribution payment landed)'), ('debit', 'Debit (an approved withdrawal or expense)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='funerals.contributionpayment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='funerals.ledgerwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgerwallet',
            constraint=models.UniqueConstraint(fields=('community', 'scope', 'family'), name='one_ledger_wallet_per_community_scope_family'),
        ),
        migrations.AddConstraint(
            model_name='ledgerwallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', False), ('scope', 'own_family')), models.Q(models.Q(('scope', 'own_family'), _negated=True), ('family__isnull', True)), _connector='OR'), name='ledger_wallet_family_set_iff_family_scoped'),
        ),
    ]
