# Generated by Django 6.0.6 on 2026-09-09 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0019_funeralevent_town_elder_chief_amount_and_more'),
        ('members', '0010_member_town_elder_individual_rate'),
        ('tenants', '0014_community_default_asupede_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='asupede_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='asupede_collection_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='asupede_collection_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AsupedeObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asupede_obligations', to='funerals.funeralevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asupede_obligations', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='AsupedePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('other', 'Other')], max_length=20)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('collector_name', models.CharField(blank=True, max_length=255)),
                ('client_op_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='funerals.asupedeobligation')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asupedeobligation',
            index=models.Index(fields=['community', 'funeral_event'], name='funerals_as_communi_94a11e_idx'),
        ),
        migrations.AddConstraint(
            model_name='asupedeobligation',
            constraint=models.UniqueConstraint(fields=('funeral_event', 'member'), name='one_asupede_obligation_per_member_per_funeral'),
        ),
    ]
