# Generated by Django 6.0.6 on 2026-09-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_bereavedrepassignment'),
        ('funerals', '0020_funeralevent_asupede_amount_and_more'),
        ('tenants', '0014_community_default_asupede_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledgerwallet',
            name='ledger_wallet_family_set_iff_family_scoped',
        ),
        migrations.AlterField(
            model_name='ledgerwallet',
            name='scope',
            field=models.CharField(choices=[('general', 'Community Ledger'), ('own_family', 'Family Ledger'), ('town_elder', 'Town Elders Ledger'), ('asupede', 'Asupedeɛ')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ledgerwallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', False), ('scope__in', ['own_family', 'asupede'])), models.Q(models.Q(('scope__in', ['own_family', 'asupede']), _negated=True), ('family__isnull', True)), _connector='OR'), name='ledger_wallet_family_set_iff_family_scoped'),
        ),
    ]
