# Generated by Django 6.0.6 on 2026-09-09 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_bereavedrepassignment'),
        ('funerals', '0021_remove_ledgerwallet_ledger_wallet_family_set_iff_family_scoped_and_more'),
        ('members', '0011_member_biological_relationship_and_more'),
        ('tenants', '0014_community_default_asupede_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InLawContributionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=255)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_law_requests', to='funerals.funeralevent')),
                ('in_law_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='families.family')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InLawObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_law_obligations', to='funerals.funeralevent')),
                ('in_law_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='families.family')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obligation', to='funerals.inlawcontributionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InLawPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('other', 'Other')], max_length=20)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('collector_name', models.CharField(blank=True, max_length=255)),
                ('client_op_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='funerals.inlawobligation')),
                ('paid_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
