# Generated by Django 6.0.6 on 2026-09-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0023_arrearscorrectionrequest'),
        ('members', '0012_member_father_name_member_hometown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='cause_of_death',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='deceased_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funerals_as_deceased', to='members.member'),
        ),
    ]
