# Generated by Django 6.0.6 on 2026-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0024_funeralevent_cause_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='funeral_type',
            field=models.CharField(choices=[('contributions', 'Funeral contributions'), ('asupede', 'Asupedeɛ')], default='contributions', max_length=16),
        ),
    ]
