# Generated by Django 6.0.6 on 2026-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('defaulter_escalation', 'Defaulter Escalation'), ('family_expense_approval', 'Family Expense Approval')], max_length=40),
        ),
    ]
