# Generated by Django 6.0.6 on 2026-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('defaulter_escalation', 'Defaulter Escalation'), ('family_expense_approval', 'Family Expense Approval'), ('old_debt', 'Old Debt Alert')], max_length=40),
        ),
    ]
