# Generated by Django 6.0.6 on 2026-09-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('defaulter_escalation', 'Defaulter Escalation'), ('family_expense_approval', 'Family Expense Approval'), ('old_debt', 'Old Debt Alert'), ('birthday', 'Birthday'), ('welfare_campaign_launched', 'Welfare Campaign Launched'), ('subscription_reminder', 'Subscription Reminder'), ('notice_board_post', 'Notice Board Post')], max_length=40),
        ),
    ]
