# Generated by Django 6.0.6 on 2026-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributioncampaign',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('family_approved', 'Family-Approved, Awaiting Community Admin'), ('active', 'Active'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
