# Generated by Django 6.0.6 on 2026-09-09 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_biological_relationship_and_more'),
        ('welfare', '0003_welfarerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contributioncampaign',
            name='target_type',
            field=models.CharField(choices=[('all_eligible', 'All Eligible Members'), ('town_elders', 'Town Elders Only'), ('selected_members', 'Selected Members')], default='all_eligible', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignTargetMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_members', to='welfare.contributioncampaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'member'), name='one_target_row_per_member_per_campaign')],
            },
        ),
    ]
