# Generated by Django 6.0.6 on 2026-07-04 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('renamed', 'Renamed'), ('merged', 'Merged'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('deleted', 'Deleted'), ('head_assigned', 'Family Head Assigned'), ('member_transferred_in', 'Member Transferred In'), ('member_transferred_out', 'Member Transferred Out'), ('rate_recommended', 'Own-Family Rate Recommended'), ('rate_approved', 'Own-Family Rate Approved'), ('rate_rejected', 'Own-Family Rate Rejected')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('merged', 'Merged into another family'), ('deleted', 'Soft-deleted')], default='active', max_length=20)),
                ('recommended_family_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Proposed by the Family Head; not yet in effect until approved.', max_digits=10, null=True)),
                ('standing_family_rate', models.DecimalField(blank=True, decimal_places=2, help_text='The approved, currently-effective own-family contribution amount.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='tenants.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
