# Generated by Django 6.0.6 on 2026-07-04 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('members', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_of_family', to='members.member'),
        ),
        migrations.AddField(
            model_name='family',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed_families', to='families.family'),
        ),
        migrations.AddField(
            model_name='familyauditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyauditlog',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community'),
        ),
        migrations.AddField(
            model_name='familyauditlog',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='families.family'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['community', 'status'], name='families_fa_communi_251c8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('community', 'name'), name='unique_active_family_name_per_community'),
        ),
    ]
