# Generated by Django 6.0.6 on 2026-07-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_initial'),
        ('members', '0003_member_linked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_of_family', to='members.member'),
        ),
        migrations.AddField(
            model_name='family',
            name='family_treasurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_of_family', to='members.member'),
        ),
        migrations.AlterField(
            model_name='familyauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('renamed', 'Renamed'), ('merged', 'Merged'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('deleted', 'Deleted'), ('head_assigned', 'Family Head Assigned'), ('officer_assigned', 'Family Officer (Secretary/Treasurer) Assigned'), ('member_transferred_in', 'Member Transferred In'), ('member_transferred_out', 'Member Transferred Out'), ('rate_recommended', 'Own-Family Rate Recommended'), ('rate_approved', 'Own-Family Rate Approved'), ('rate_rejected', 'Own-Family Rate Rejected')], max_length=32),
        ),
    ]
