# Generated by Django 6.0.6 on 2026-07-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_familyofficerposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('renamed', 'Renamed'), ('merged', 'Merged'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('deleted', 'Deleted'), ('head_assigned', 'Family Head Assigned'), ('officer_assigned', 'Family Officer (Secretary/Treasurer) Assigned'), ('officer_position_appointed', 'Family Executive Position Appointed'), ('officer_position_removed', 'Family Executive Position Removed'), ('member_transferred_in', 'Member Transferred In'), ('member_transferred_out', 'Member Transferred Out'), ('rate_recommended', 'Own-Family Rate Recommended'), ('rate_approved', 'Own-Family Rate Approved'), ('rate_rejected', 'Own-Family Rate Rejected')], max_length=32),
        ),
    ]
