# Generated by Django 6.0.6 on 2026-07-07 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_initial'),
        ('funerals', '0002_contributionpayment_printed_at'),
        ('members', '0003_member_linked_user'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='members.member')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='families.family')),
                ('funeral_event', models.ForeignKey(blank=True, help_text="Optional — many tasks ('welcome guests', 'arrange chairs') are tied to a specific funeral.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='funerals.funeralevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['community', 'assigned_to'], name='tasks_membe_communi_9d34e7_idx')],
            },
        ),
    ]
