# Generated by Django 6.0.6 on 2026-07-23 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_announcement_featured_on_homepage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('community', 'Community Lifecycle'), ('role', 'Role Assignment'), ('funeral_opening', 'Funeral Opening Decision'), ('payment_reversal', 'Payment Reversal Decision'), ('billing', 'Platform Billing'), ('announcement', 'Announcement / Homepage Feature')], max_length=30)),
                ('action', models.CharField(max_length=100)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.community')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['community', '-created_at'], name='audit_log_a_communi_987a7c_idx'), models.Index(fields=['category', '-created_at'], name='audit_log_a_categor_40c4d4_idx')],
            },
        ),
    ]
