"""
Django settings for nsaabodeeq project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-h&gu5%rt&8ci)*h*bj)lwm2q-k#b!uwao7-ksm)lt4)-4my4l(',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Defaults now bake in this project's real, known Railway host and
# Vercel origin directly — not just localhost — so a fresh Railway
# deploy (or one where these environment variables get lost or reset)
# still works correctly out of the box, without depending on every
# deploy remembering to set DJANGO_ALLOWED_HOSTS / CORS_ALLOWED_ORIGINS
# by hand. The environment variable, when set, still fully overrides
# this — it's a safety net, not a replacement for configuring these
# properly in a genuinely new environment.
_default_hosts = "localhost,127.0.0.1,nsaabodee-smart-production.up.railway.app,nsaabodee-smart.railway.internal"
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', _default_hosts).split(',') if h.strip()
]

# 'Failed to fetch' in the browser, on every single API call, was this:
# django-cors-headers was never actually installed or configured, even
# though the frontend (localhost:3000) and backend (localhost:8000) are
# different origins as far as a browser is concerned — automated tests
# never caught this because DRF's APIClient talks to the backend
# directly, server-side, with no browser CORS enforcement involved at
# all. This is the first time a real browser ever made a real
# cross-origin request against a real running backend in this project.
#
# CORS_ALLOWED_ORIGINS defaults to the local dev frontend AND this
# project's real Vercel URL together, so both `npm run dev` locally
# and the actual deployed frontend work with zero required
# configuration; the CORS_ALLOWED_ORIGINS environment variable, when
# set, still fully overrides this.
_default_cors = "http://localhost:3000,https://nsaabodee-smart.vercel.app"
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', _default_cors).split(',') if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True

# The real, public frontend URL — used to build genuinely scannable QR
# codes (member cards, funeral contribution codes) that open in any
# ordinary phone camera, not a custom app-only URI scheme. Defaults to
# the first CORS-allowed origin, since that's already the frontend's
# real address in every environment this platform runs in.
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', CORS_ALLOWED_ORIGINS[0] if CORS_ALLOWED_ORIGINS else 'http://localhost:3000')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'tenants',
    'accounts',
    'members',
    'families',
    'funerals',
    'contribution_rules',
    'notifications',
    'gifts',
    'funeral_logistics',
    'reports',
    'communication',
    'dashboard',
    'realtime',
    'messaging',
    'audit_log',
    'support',
    'payments',
    'ai_features',
    'tasks',
    'family_funds',
    'welfare',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nsaabodeeq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nsaabodeeq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # dj_database_url.config() reads the single DATABASE_URL environment
    # variable Railway (and most other PaaS providers) automatically set
    # the moment a Postgres service is attached — this is the standard,
    # correct way to pick that up. The previous version of this setting
    # expected separate DB_ENGINE/DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/
    # DB_PORT variables instead, none of which Railway actually sets by
    # default — meaning Postgres was silently never being connected to
    # at all, and every deploy was falling back to a fresh, ephemeral
    # SQLite file that Railway's non-persistent filesystem wipes on
    # every restart. That's the real, underlying reason demo data and
    # migrations kept appearing to vanish. Falls back to a local SQLite
    # file when DATABASE_URL isn't set at all (local development).
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    # Missing entirely until a real file upload (a User's profile photo,
    # via a genuine multipart request, not a test fixture setting
    # `photo=None`) actually exercised this code path for the first time
    # in the whole project — Django 5.1+ requires "default" explicitly
    # once STORAGES is used at all; it doesn't silently fall back to
    # FileSystemStorage the way the older DEFAULT_FILE_STORAGE setting
    # used to. Member.photo has been an ImageField since early in this
    # build and would have hit this exact error the moment anyone
    # uploaded a real photo — no test ever saved an actual file object
    # through it, only ever `photo=None` in Python test setups.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

# --- Communication Module: real provider credentials -----------------
# None of these have real values in this environment. Every provider in
# communication/providers.py checks for its own required settings and
# raises ProviderNotConfiguredError (caught and recorded, never crashing
# a request) if they're missing — so leaving these unset is always safe,
# just inert. Fill in real values (ideally from environment variables in
# production, never committed to source control) to actually turn a
# channel on.

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
# Uncomment and configure for a real mail server; Django defaults to
# printing emails to the console otherwise, which is safe but not real delivery.
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.environ.get('EMAIL_HOST')
# EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
# EMAIL_USE_TLS = True

TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN')
TWILIO_FROM_NUMBER = os.environ.get('TWILIO_FROM_NUMBER')

WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID')

# --- API-wide settings: auth + pagination -----------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.CommunityAwareJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Every list endpoint in this platform — Family, Member, FuneralEvent,
    # ContributionObligation, GiftDonation, Notification, DeliveryAttempt
    # — returns through this, so a community with thousands of members
    # never sends (or a phone never has to receive) an unbounded JSON
    # array. 25 is deliberately small: this is a funeral-records app read
    # mostly on phones over patchy connections, not a bulk data export tool.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    # Short-lived access token; a mobile collector's app silently uses
    # the refresh token to get a new one rather than forcing a re-login
    # mid-shift. Refresh tokens are rotated and blacklisted on use/logout
    # (token_blacklist app, migrated above) so a stolen refresh token
    # from a lost phone can be invalidated by revoking it, not just by
    # waiting for it to expire on its own.
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# --- Celery (async task queue) ----------------------------------------
# Backs the notification-delivery and defaulter-evaluation work moved
# off the request/response cycle in the Communication/Members passes —
# see funerals/tasks.py and members/tasks.py. CELERY_TASK_ALWAYS_EAGER
# defaults True so tests and local `python manage.py runserver` work
# with zero extra setup (tasks just run synchronously in-process); set
# it False (and point CELERY_BROKER_URL at a real Redis) to actually get
# asynchronous, out-of-process execution via `celery -A nsaabodeeq worker`.
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'True') == 'True'

# --- Django Channels (WebSockets) --------------------------------------
# Backs live updates: a payment recorded on one collector's phone shows
# up on another device watching the same funeral's ledger without a
# manual refresh (see realtime/consumers.py). channels_redis is the
# production channel layer (a real pub/sub backend so multiple server
# processes/machines can all broadcast to the same group); tests
# override this to the in-memory layer (see realtime/tests) so CI
# doesn't need a live Redis just to prove the consumer logic is correct.
ASGI_APPLICATION = 'nsaabodeeq.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.environ.get('CHANNEL_LAYERS_REDIS_URL', 'redis://localhost:6379/1')],
        },
    },
}

# --- Mobile Money collection, via Paystack --------------------------
# See payments/providers.py. Paystack's own unified Charge API handles
# MTN, Vodafone, and AirtelTigo mobile money in Ghana through one
# integration, rather than this platform maintaining a direct
# integration against each telco's own API individually. Left unset,
# PaystackMomoProvider raises a clear, caught ProviderNotConfiguredError
# instead of silently doing nothing.
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY')

# Verifies that an incoming /api/payments/paystack/webhook/ request
# genuinely came from Paystack (HMAC-SHA512 of the raw request body,
# keyed with this same secret key) before ever trusting its contents —
# see payments/views.py's PaystackWebhookView.

# --- AI Features: meeting summarization (Anthropic Messages API) ------
# See ai_features/llm_provider.py. Left unset by default; summarize
# raises a clear, caught error instead of silently doing nothing.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')
ANTHROPIC_MODEL = os.environ.get('ANTHROPIC_MODEL', 'claude-sonnet-4-5')

# --- Demo Access ("Try a live demo" login buttons) ---------------------
# Defaults True for local dev/evaluation, per accounts/management/commands/seed_demo_data.py.
# A real production deployment should set this False in its environment
# — this endpoint deliberately bypasses password checking entirely, so
# leaving it on in production would let anyone log in as a demo
# Community Admin without credentials.
DEMO_MODE_ENABLED = os.environ.get('DEMO_MODE_ENABLED', 'True') == 'True'
