# Generated by Django 6.0.6 on 2026-07-05 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('console', 'Console (development log)'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient_address', models.CharField(blank=True, help_text='Email address or phone number attempted, if any.', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped_not_configured', 'Skipped — Channel Not Configured'), ('skipped_no_address', 'Skipped — No Contact Address'), ('failed', 'Failed')], max_length=30)),
                ('provider_response', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notification')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
