# Generated by Django 6.0.6 on 2026-07-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_communitymeeting'),
        ('families', '0005_alter_familyauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymeeting',
            name='family',
            field=models.ForeignKey(blank=True, help_text="Null for a community-wide meeting; set for a single family's own meeting.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='families.family'),
        ),
    ]
