# Generated by Django 6.0.6 on 2026-07-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_communitymeeting_family'),
        ('funerals', '0011_funeralcommitteeposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymeeting',
            name='funeral_event',
            field=models.ForeignKey(blank=True, help_text="Set for a single funeral's own committee meeting.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='funerals.funeralevent'),
        ),
    ]
