# Generated by Django 6.0.6 on 2026-07-05 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0002_contributionpayment_printed_at'),
        ('members', '0003_member_linked_user'),
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='momopaymentrequest',
            name='donor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='momopaymentrequest',
            name='funeral_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momo_gift_requests', to='funerals.funeralevent'),
        ),
        migrations.AddField(
            model_name='momopaymentrequest',
            name='received_by_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member'),
        ),
        migrations.AddField(
            model_name='momopaymentrequest',
            name='target_type',
            field=models.CharField(choices=[('contribution', 'Mandatory Contribution'), ('gift', 'Gift / Donation')], default='contribution', max_length=20),
        ),
        migrations.AlterField(
            model_name='momopaymentrequest',
            name='obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momo_requests', to='funerals.contributionobligation'),
        ),
        migrations.AddConstraint(
            model_name='momopaymentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('funeral_event__isnull', True), ('obligation__isnull', False), ('target_type', 'contribution')), models.Q(('funeral_event__isnull', False), ('obligation__isnull', True), ('target_type', 'gift')), _connector='OR'), name='momo_request_has_exactly_one_target'),
        ),
    ]
