# Generated by Django 6.0.6 on 2026-07-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_momopaymentrequest_donor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momopaymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_otp', 'Awaiting OTP'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
