# Generated by Django 6.0.6 on 2026-09-09 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funerals', '0018_ledgerwallet_ledgerwallettransaction_and_more'),
        ('members', '0009_collectornomination_collectorapproval'),
        ('payments', '0003_alter_momopaymentrequest_status'),
        ('tenants', '0012_community_required_funeral_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='momopaymentrequest',
            name='momo_request_has_exactly_one_target',
        ),
        migrations.AddField(
            model_name='momopaymentrequest',
            name='deposit_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momo_wallet_deposit_requests', to='members.member'),
        ),
        migrations.AlterField(
            model_name='momopaymentrequest',
            name='target_type',
            field=models.CharField(choices=[('contribution', 'Mandatory Contribution'), ('gift', 'Gift / Donation'), ('wallet_deposit', 'Member Wallet Deposit')], default='contribution', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='momopaymentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit_member__isnull', True), ('funeral_event__isnull', True), ('obligation__isnull', False), ('target_type', 'contribution')), models.Q(('deposit_member__isnull', True), ('funeral_event__isnull', False), ('obligation__isnull', True), ('target_type', 'gift')), models.Q(('deposit_member__isnull', False), ('funeral_event__isnull', True), ('obligation__isnull', True), ('target_type', 'wallet_deposit')), _connector='OR'), name='momo_request_has_exactly_one_target'),
        ),
    ]
