# Generated by Django 6.0.6 on 2026-07-04 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaulterPolicy',
            fields=[
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='defaulter_policy', serialize=False, to='tenants.community')),
                ('warning_threshold', models.PositiveIntegerField(default=1)),
                ('high_warning_threshold', models.PositiveIntegerField(default=2)),
                ('flag_threshold', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRateChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_male_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_female_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_male_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_female_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_rate_changes', to='tenants.community')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberStatusRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('is_exempt', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_status_rules', to='tenants.community')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('community', 'status'), name='one_rule_per_status_per_community')],
            },
        ),
    ]
