# Generated by Django 6.0.6 on 2026-09-29 10:47

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0006_bereavedrepassignment'),
        ('tenants', '0024_community_role_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('minutes', 'Meeting minutes'), ('statement', 'Financial statement'), ('receipt', 'Receipt / invoice'), ('register', 'Register / list'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(max_length=300, upload_to=documents.models._upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.community')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='families.family')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
