# Generated by Django 6.0.6 on 2026-07-04 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_number', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('ghana_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('missed_contributions_count', models.PositiveIntegerField(default=0)),
                ('defaulter_tier', models.CharField(choices=[('none', 'In Good Standing'), ('warning', 'Warning'), ('high_warning', 'High Warning'), ('flagged', 'Flagged')], default='none', max_length=20)),
                ('defaulter_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.community')),
                ('family', models.ForeignKey(blank=True, help_text='Every member belongs to at most one family. Null only transiently after a forced family deletion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='families.family')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['community', 'status'], name='members_mem_communi_910c07_idx'), models.Index(fields=['community', 'defaulter_tier'], name='members_mem_communi_f49752_idx'), models.Index(fields=['community', 'full_name'], name='members_mem_communi_0cb39e_idx')],
                'constraints': [models.UniqueConstraint(fields=('community', 'membership_number'), name='unique_membership_number_per_community'), models.UniqueConstraint(condition=models.Q(('ghana_card_number__isnull', False)), fields=('community', 'ghana_card_number'), name='unique_ghana_card_per_community')],
            },
        ),
    ]
