# Generated by Django 6.0.6 on 2026-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
