# Generated by Django 6.0.6 on 2026-07-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='family_seniority',
            field=models.CharField(choices=[('senior', 'Senior (uncle-tier)'), ('junior', 'Junior (nephew-tier)')], default='junior', help_text="Which own-family contribution tier this member pays (male members only; women pay the family's woman rate regardless). Ignored for the family head, whose rate is always the head rate.", max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='is_town_leader',
            field=models.BooleanField(default=False, help_text="Chief or elder — pays the community's flat town-leader contribution rate instead of the usual family/general rate, regardless of which family they belong to."),
        ),
    ]
