# Generated by Django 6.0.6 on 2026-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_memberwallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='town_elder_title',
            field=models.CharField(blank=True, choices=[('chief', 'Chief'), ('queen_mother', 'Queen Mother'), ('linguist', 'Linguist'), ('other', 'Other Town Executive')], max_length=20, null=True),
        ),
    ]
