# Generated by Django 6.0.6 on 2026-09-08 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_bereavedrepassignment'),
        ('members', '0008_member_town_elder_title'),
        ('tenants', '0012_community_required_funeral_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorNomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collector_type', models.CharField(choices=[('general', 'General Collector (community ledger)'), ('family', 'Family Collector (family ledger)'), ('donation', 'Donation Collector (gift ledger)'), ('town_elder', 'Town Elders Collector')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_nominations', to='tenants.community')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_nominations', to='members.member')),
                ('nominated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scoped_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='families.family')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectorApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='members.collectornomination')),
            ],
            options={
                'ordering': ['decided_at'],
                'constraints': [models.UniqueConstraint(fields=('nomination', 'decided_by'), name='one_decision_per_approver_per_nomination')],
            },
        ),
    ]
