# Generated by Django 6.0.6 on 2026-09-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_collectornomination_collectorapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='town_elder_individual_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
