# Generated by Django 6.0.6 on 2026-09-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_town_elder_individual_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='biological_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('cousin', 'Cousin'), ('spouse', 'Spouse'), ('parent_in_law', 'Parent-in-law'), ('sibling_in_law', 'Sibling-in-law'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='family_position',
            field=models.CharField(blank=True, choices=[('family_head', 'Family Head'), ('senior_family_member', 'Senior Family Member'), ('parent_generation', 'Parent Generation'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('son', 'Son'), ('daughter', 'Daughter'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('spouse', 'Spouse'), ('in_law', 'In-Law'), ('dependant', 'Dependant'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation_status',
            field=models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('apprentice', 'Apprentice')], default='none', max_length=20),
        ),
    ]
