import 'dart:convert';
import 'dart:typed_data';

import 'package:http/http.dart' as http;

class ReportsApiClient {
  final String baseUrl;
  final Future<Map<String, String>> Function() authHeaders;

  ReportsApiClient({required this.baseUrl, required this.authHeaders});

  Future<String> contributionReceiptText(String paymentId) async {
    final headers = await authHeaders();
    final res = await http.get(Uri.parse('$baseUrl/api/receipts/contribution-payments/$paymentId/text/'), headers: headers);
    if (res.statusCode >= 400) throw Exception('Could not load receipt (${res.statusCode})');
    return res.body;
  }

  Future<String> giftReceiptText(String donationId) async {
    final headers = await authHeaders();
    final res = await http.get(Uri.parse('$baseUrl/api/receipts/gift-donations/$donationId/text/'), headers: headers);
    if (res.statusCode >= 400) throw Exception('Could not load receipt (${res.statusCode})');
    return res.body;
  }

  /// Raw PDF bytes for a receipt — the same file the web frontend's
  /// "Download PDF" link opens, generated by `reports/pdf.py` on the
  /// backend. The caller is responsible for writing these to a temp file
  /// and opening it (see ReceiptViewScreen's `_openPdf`), since actually
  /// rendering/sharing a PDF is a platform-integration concern (a
  /// package like `open_filex` or `printing`), not something this HTTP
  /// client should decide on the app's behalf.
  Future<Uint8List> contributionReceiptPdfBytes(String paymentId) async {
    final headers = await authHeaders();
    final res = await http.get(Uri.parse('$baseUrl/api/receipts/contribution-payments/$paymentId/pdf/'), headers: headers);
    if (res.statusCode >= 400) throw Exception('Could not load the receipt PDF (${res.statusCode})');
    return res.bodyBytes;
  }

  Future<Uint8List> giftReceiptPdfBytes(String donationId) async {
    final headers = await authHeaders();
    final res = await http.get(Uri.parse('$baseUrl/api/receipts/gift-donations/$donationId/pdf/'), headers: headers);
    if (res.statusCode >= 400) throw Exception('Could not load the receipt PDF (${res.statusCode})');
    return res.bodyBytes;
  }

  /// The structured JSON form of a receipt — same data the on-screen
  /// text view and the PDF both come from — used here as the input to
  /// building the ESC/POS bytes for an actual thermal printer.
  Future<Map<String, dynamic>> contributionReceiptData(String paymentId) async {
    final headers = await authHeaders();
    final res = await http.get(Uri.parse('$baseUrl/api/receipts/contribution-payments/$paymentId/'), headers: headers);
    if (res.statusCode >= 400) throw Exception('Could not load receipt (${res.statusCode})');
    return jsonDecode(res.body) as Map<String, dynamic>;
  }

  Future<Map<String, dynamic>> giftReceiptData(String donationId) async {
    final headers = await authHeaders();
    final res = await http.get(Uri.parse('$baseUrl/api/receipts/gift-donations/$donationId/'), headers: headers);
    if (res.statusCode >= 400) throw Exception('Could not load receipt (${res.statusCode})');
    return jsonDecode(res.body) as Map<String, dynamic>;
  }

  /// Confirms the physical slip was actually handed over — see
  /// ReceiptPrinterService and reports.services.unprinted_receipts on
  /// the backend for why this matters beyond just bookkeeping.
  Future<void> markContributionReceiptPrinted(String paymentId) async {
    final headers = await authHeaders();
    final res = await http.post(
      Uri.parse('$baseUrl/api/receipts/contribution-payments/$paymentId/mark-printed/'),
      headers: headers,
    );
    if (res.statusCode >= 400) throw Exception('Could not confirm the receipt as printed (${res.statusCode})');
  }

  Future<void> markGiftReceiptPrinted(String donationId) async {
    final headers = await authHeaders();
    final res = await http.post(
      Uri.parse('$baseUrl/api/receipts/gift-donations/$donationId/mark-printed/'),
      headers: headers,
    );
    if (res.statusCode >= 400) throw Exception('Could not confirm the receipt as printed (${res.statusCode})');
  }
}
