# Generated by Django 6.0.6 on 2026-07-05 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funerals', '0002_contributionpayment_printed_at'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousTransactionFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('amount_outlier', 'Unusual amount for this collector'), ('rapid_succession', 'Many payments in rapid succession')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('confirmed', 'Confirmed genuine concern'), ('dismissed', 'Dismissed — false positive')], default='unreviewed', max_length=20)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicion_flags', to='funerals.contributionpayment')),
            ],
            options={
                'ordering': ['-flagged_at'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'reason'), name='one_flag_per_payment_per_reason')],
            },
        ),
    ]
