import 'dart:convert';

import 'package:flutter/material.dart';

import '../data/members_api_client.dart';
import '../domain/member.dart';

class MemberCardScreen extends StatefulWidget {
  final MembersApiClient apiClient;
  final Member member;

  const MemberCardScreen({super.key, required this.apiClient, required this.member});

  @override
  State<MemberCardScreen> createState() => _MemberCardScreenState();
}

class _MemberCardScreenState extends State<MemberCardScreen> {
  Map<String, dynamic>? _card;
  String? _error;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    if (widget.member.pendingSync) {
      setState(() => _error = "This member hasn't synced yet — the digital card and QR "
          "code are generated by the server once connected.");
      return;
    }
    try {
      final card = await widget.apiClient.card(widget.member.id);
      if (!mounted) return;
      setState(() => _card = card);
    } catch (e) {
      if (!mounted) return;
      setState(() => _error = e.toString());
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Digital membership card')),
      body: Center(
        child: _error != null
            ? Padding(padding: const EdgeInsets.all(24), child: Text(_error!, textAlign: TextAlign.center))
            : _card == null
                ? const CircularProgressIndicator()
                : Card(
                    margin: const EdgeInsets.all(24),
                    child: Padding(
                      padding: const EdgeInsets.all(24),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          CircleAvatar(
                            radius: 36,
                            backgroundImage: _card!['photo_url'] != null
                                ? NetworkImage(_card!['photo_url'] as String)
                                : null,
                            child: _card!['photo_url'] == null
                                ? Text((_card!['full_name'] as String).substring(0, 1))
                                : null,
                          ),
                          const SizedBox(height: 12),
                          Text(_card!['full_name'] as String, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                          Text(_card!['membership_number'] as String, style: const TextStyle(fontFamily: 'monospace')),
                          if (_card!['family_name'] != null) Text(_card!['family_name'] as String),
                          const SizedBox(height: 16),
                          Image.memory(
                            base64Decode(_card!['qr_code_base64'] as String),
                            width: 160,
                            height: 160,
                          ),
                          const SizedBox(height: 8),
                          const Text('Nsaabodeɛ Smart', style: TextStyle(fontSize: 12, color: Colors.grey)),
                        ],
                      ),
                    ),
                  ),
      ),
    );
  }
}
