# Generated by Django 6.0.6 on 2026-07-04 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funerals', '0001_initial'),
        ('members', '0002_alter_member_membership_number'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=255)),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='funerals.funeralevent')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funeral_attendance', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attended_at'],
                'indexes': [models.Index(fields=['community', 'funeral_event'], name='funeral_log_communi_305930_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('funeral_event', 'member'), name='one_attendance_record_per_member_per_funeral')],
            },
        ),
        migrations.CreateModel(
            name='FuneralExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('catering', 'Catering'), ('transport', 'Transport'), ('coffin', 'Coffin'), ('venue', 'Venue / Canopy / Chairs'), ('printing', 'Printing (posters, programs)'), ('burial_fees', 'Cemetery / Burial Fees'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('other', 'Other')], default='cash', max_length=20)),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('incurred_on', models.DateField()),
                ('client_op_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='funerals.funeralevent')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incurred_on'],
                'indexes': [models.Index(fields=['community', 'funeral_event'], name='funeral_log_communi_acecdf_idx')],
            },
        ),
    ]
