# Generated by Django 6.0.6 on 2026-07-24 00:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeral_logistics', '0001_initial'),
        ('members', '0006_member_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralexpense',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member'),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='expense_invoices/'),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('credit', 'Credit (Owed to Supplier)'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='funeralexpense',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
