# Generated by Django 6.0.6 on 2026-08-12 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeral_logistics', '0002_funeralexpense_amount_paid_and_more'),
        ('funerals', '0014_funeraldeskassignmentapproval'),
        ('tenants', '0012_community_required_funeral_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralExpenseFund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.community')),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('funeral_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_fund_deposits', to='funerals.funeralevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
