from django.urls import path

from .views import (
    ApproveAnnouncementView,
    BillingRecordsView,
    CommunityAdminsView,
    PlatformAdminsView,
    MyCommunityBrandingView,
    MyCommunityLogoView,
    MyApprovalWorkflowView,
    CommunityTerminateAccessView,
    ResetAdministratorPasswordView,
    CommunityAnnouncementsView,
    CommunityDeactivateView,
    CommunityDetailView,
    CommunityExtendAccessView,
    CommunityListView,
    CommunityMakePermanentView,
    CommunityReactivateView,
    DeactivatePayoutAccountView,
    HomepageImageDeactivateView,
    HomepageImagesManageView,
    HomepageImagesPublicView,
    MarkBillingRecordPaidView,
    MarkPlanInterestContactedView,
    HomepageFeaturedAnnouncementsView,
    NoticeBoardView,
    PayoutAccountsView,
    PendingAnnouncementsReviewView,
    PlanInterestSubmissionsView,
    RejectAnnouncementView,
    ResubmitAnnouncementView,
    SubmitAnnouncementView,
    SubmitPlanInterestView,
    WaiveBillingRecordView,
    PlatformRevenueReportView,
    FeatureFlagsView,
    ToggleFeatureFlagView,
    FeatureFlagStatusView,
)

urlpatterns = [
    path("tenants/communities/", CommunityListView.as_view(), name="tenant-community-list"),
    path("tenants/communities/<uuid:community_id>/", CommunityDetailView.as_view(), name="tenant-community-detail"),
    path("tenants/communities/<uuid:community_id>/deactivate/", CommunityDeactivateView.as_view(), name="tenant-community-deactivate"),
    path("tenants/communities/<uuid:community_id>/reactivate/", CommunityReactivateView.as_view(), name="tenant-community-reactivate"),
    path("tenants/communities/<uuid:community_id>/extend-access/", CommunityExtendAccessView.as_view(), name="tenant-community-extend-access"),
    path("tenants/communities/<uuid:community_id>/make-permanent/", CommunityMakePermanentView.as_view(), name="tenant-community-make-permanent"),
    path("tenants/communities/<uuid:community_id>/admins/", CommunityAdminsView.as_view(), name="tenant-community-admins"),
    path("tenants/platform-admins/", PlatformAdminsView.as_view(), name="tenant-platform-admins"),
    path("tenants/my-community/branding/", MyCommunityBrandingView.as_view(), name="tenant-my-community-branding"),
    path("tenants/my-community/logo/", MyCommunityLogoView.as_view(), name="tenant-my-community-logo"),
    path("tenants/my-community/approval-workflow/", MyApprovalWorkflowView.as_view(), name="tenant-my-approval-workflow"),
    path("tenants/communities/<uuid:community_id>/terminate-access/", CommunityTerminateAccessView.as_view(), name="tenant-community-terminate-access"),
    path("tenants/reset-admin-password/", ResetAdministratorPasswordView.as_view(), name="tenant-reset-admin-password"),
    path("tenants/communities/<uuid:community_id>/payout-accounts/", PayoutAccountsView.as_view(), name="tenant-community-payout-accounts"),
    path("tenants/communities/<uuid:community_id>/payout-accounts/<uuid:account_id>/deactivate/", DeactivatePayoutAccountView.as_view(), name="tenant-community-payout-account-deactivate"),
    path("tenants/communities/<uuid:community_id>/billing-records/", BillingRecordsView.as_view(), name="tenant-community-billing-records"),
    path("tenants/communities/<uuid:community_id>/billing-records/<uuid:record_id>/mark-paid/", MarkBillingRecordPaidView.as_view(), name="tenant-community-billing-record-mark-paid"),
    path("tenants/communities/<uuid:community_id>/billing-records/<uuid:record_id>/waive/", WaiveBillingRecordView.as_view(), name="tenant-community-billing-record-waive"),
    path("tenants/platform-revenue/", PlatformRevenueReportView.as_view(), name="tenant-platform-revenue"),
    path("tenants/feature-flags/", FeatureFlagsView.as_view(), name="tenant-feature-flags"),
    path("tenants/feature-flags/<slug:key>/toggle/", ToggleFeatureFlagView.as_view(), name="tenant-feature-flag-toggle"),
    path("tenants/feature-flags/status/", FeatureFlagStatusView.as_view(), name="tenant-feature-flag-status"),
    path("tenants/homepage-images/", HomepageImagesPublicView.as_view(), name="tenant-homepage-images-public"),
    path("tenants/homepage-images/manage/", HomepageImagesManageView.as_view(), name="tenant-homepage-images-manage"),
    path("tenants/homepage-images/<uuid:image_id>/deactivate/", HomepageImageDeactivateView.as_view(), name="tenant-homepage-image-deactivate"),
    path("tenants/plan-interest/", SubmitPlanInterestView.as_view(), name="tenant-plan-interest-submit"),
    path("tenants/plan-interest/manage/", PlanInterestSubmissionsView.as_view(), name="tenant-plan-interest-manage"),
    path("tenants/plan-interest/<uuid:submission_id>/mark-contacted/", MarkPlanInterestContactedView.as_view(), name="tenant-plan-interest-mark-contacted"),
    path("tenants/communities/<uuid:community_id>/announcements/", CommunityAnnouncementsView.as_view(), name="tenant-community-announcements"),
    path("tenants/communities/<uuid:community_id>/announcements/submit/", SubmitAnnouncementView.as_view(), name="tenant-announcement-submit"),
    path("tenants/announcements/<uuid:announcement_id>/resubmit/", ResubmitAnnouncementView.as_view(), name="tenant-announcement-resubmit"),
    path("tenants/announcements/pending-review/", PendingAnnouncementsReviewView.as_view(), name="tenant-announcements-pending-review"),
    path("tenants/announcements/<uuid:announcement_id>/approve/", ApproveAnnouncementView.as_view(), name="tenant-announcement-approve"),
    path("tenants/announcements/<uuid:announcement_id>/reject/", RejectAnnouncementView.as_view(), name="tenant-announcement-reject"),
    path("tenants/notice-board/", NoticeBoardView.as_view(), name="tenant-notice-board"),
    path("tenants/notice-board/homepage-featured/", HomepageFeaturedAnnouncementsView.as_view(), name="tenant-notice-board-homepage-featured"),
]
